#  To run use:
# ageval -m -cd exp/configs/<CONFIGDIR>
num_workers: 16
hydra:
  launcher:
    n_jobs: 2
  mode: MULTIRUN
  sweeper:
    params:
      data_name: longfact-v8
      evaluator_cls: ageval.evaluators.basic.BasicPairwiseEvaluator,ageval.evaluators.baseline_arenahard.ArenaHardPairwiseEvaluator
      evaluator_kwargs.model: openai-assistant/gpt-4o-2024-05-13
      evaluator_kwargs.max_tokens: 2048
      # note that for sweep of list options, need to use choice
      # see https://hydra.cc/docs/1.3/advanced/override_grammar/extended/
      dummy: 1,2,3,4,5
defaults:
  - base_config
  - override hydra/launcher: joblib
  - _self_
